### ISSUE TITLE
Error messages from log on load

### ISSUE THREAD

**Issue by FuzzyBearBTC** [PeercoinArmory/PeercoinArmory#4]
Currently install fresh copy and dependencies and get following output from log:

(ERROR) announcefetch.py:300 - Announce info carried invalid signature!
(ERROR) announcefetch.py:301 - Signature addr: PW76rANoiP1aXD7qLRWHuS1kwsaBX8t6LZ
(ERROR) announcefetch.py:302 - Expected  address: PNBDQqpNpf6mTeV9NvcgwN7TDvZm2kxVsT
(ERROR) ArmoryQt.py:2316 - Failed to setup SDM
Traceback (most recent call last):
  File "ArmoryQt.py", line 2311, in startBitcoindIfNecessary
    TheSDM.setupSDM(extraExeSearch=self.satoshiExeSearchPath)
  File "/home/fuzzy/Dev/PeercoinArmory/SDM.py", line 345, in setupSDM
    if self.failedFindExe:  raise self.BitcoindError, 'peercoind not found'
BitcoindError: peercoind not found
(ERROR) announcefetch.py:179 - No file with ID=announce was fetched
(ERROR) announcefetch.py:179 - No file with ID=changelog was fetched
(ERROR) announcefetch.py:179 - No file with ID=downloads was fetched
(WARNING) ArmoryQt.py:1816 - No Armory links in the downloads list
(WARNING) ArmoryQt.py:1876 - No Satoshi links in the downloads list

**Comment by SigmundAlpha** [comment]
This is it not connecting to the server for update and download messages.

**Comment by FuzzyBearBTC** [comment]
running with ppcoin (original version) get this error:

(WARNING) ArmoryQt.py:2291 - Tried to start bitcoind, but satoshi already running
(ERROR) announcefetch.py:300 - Announce info carried invalid signature!
(ERROR) announcefetch.py:301 - Signature addr: PW76rANoiP1aXD7qLRWHuS1kwsaBX8t6LZ
(ERROR) announcefetch.py:302 - Expected  address: PNBDQqpNpf6mTeV9NvcgwN7TDvZm2kxVsT
(ERROR) announcefetch.py:179 - No file with ID=announce was fetched
(ERROR) announcefetch.py:179 - No file with ID=changelog was fetched
(ERROR) announcefetch.py:179 - No file with ID=downloads was fetched
(WARNING) ArmoryQt.py:1816 - No Armory links in the downloads list
(WARNING) ArmoryQt.py:1876 - No Satoshi links in the downloads list
